# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Symbol-Approx-Sub
version:      2.02
version_from: Sub.pm
installdirs:  site
requires:
    Devel::Symdump:                0
    Test::More:                    0
    Test::Pod:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
