---
name: Symbol-Approx-Sub
version: 2.04
author:
  - 'Dave Cross <dave@dave.org.uk>'
  - 'With lots of help from Leon Brocard <leon@astray.com>'
abstract: Perl module for calling subroutines by approximate names!
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Devel::Symdump: 0
  Test::More: 0
  Test::Pod: 0
provides:
  Symbol::Approx::Sub:
    file: lib/Symbol/Approx/Sub.pm
    version: 32
  Symbol::Approx::Sub::Random:
    file: lib/Symbol/Approx/Sub/Random.pm
    version: 29
  Symbol::Approx::Sub::String::Approx:
    file: lib/Symbol/Approx/Sub/String/Approx.pm
    version: 29
  Symbol::Approx::Sub::String::Equal:
    file: lib/Symbol/Approx/Sub/String/Equal.pm
    version: 29
  Symbol::Approx::Sub::Text::Metaphone:
    file: lib/Symbol/Approx/Sub/Text/Metaphone.pm
    version: 29
  Symbol::Approx::Sub::Text::Soundex:
    file: lib/Symbol/Approx/Sub/Text/Soundex.pm
    version: 29
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
